name: CI macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, closed]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout shpc
      uses: actions/checkout@v3
      with:
        submodules: true
        path: shpc

    - name: Checkout libcore
      uses: actions/checkout@v3
      with:
        submodules: true
        repository: VertexFusion/libcore
        path: libcore

    - name: make
      run: | 
         cd shpc
         make
         cd ..
      
    - name: run test
      run: | 
         cd shpc
         ./bin/shpc -test
         cd ..